[functions.device-token-android]
verify_jwt = true

[functions.device-token-ios]
verify_jwt = true

[functions.verify-android]
verify_jwt = false

[functions.verify-ios]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.dispatch-notifications]
verify_jwt = true

[functions.notification-event]
verify_jwt = false
