sonar.projectKey=Limgrow-Server_System-tracking-Fox-Limgrow
sonar.organization=limgrow-server

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/dist/**,**/build/**,**/coverage/**,**/*.config.js,**/*.config.mjs,**/*.config.ts

sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info